run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - ineffassign
    - gosimple
    - errcheck

linters-settings:
  errcheck:
    exclude-functions: []

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
