version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - ineffassign
    - errcheck

  settings:
    staticcheck:
      checks: ["all"]
    errcheck:
      exclude-functions: []

  exclusions:
    presets: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
