name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Go ${{ matrix.go }} (stable)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.24.x']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: false
          cache: true
          cache-dependency-path: go.sum

      - name: go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.3.1
          args: --timeout=5m
          skip-cache: false

      - name: test
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.go }}
          path: coverage.out
          if-no-files-found: error

  
  test-rc:
  continue-on-error: true
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25.0-rc.1'
        cache: true
        cache-dependency-path: go.sum
    - run: go build ./...
    - run: go test ./... -run=^$ || true